server:
  port: 8090

spring:
  profiles:
    active: dev
  application:
    name: spring-restful-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# spring boot mybatis 自动配置
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.ifsaid.shark.entity
mapper:
  identity: MYSQL
  mappers: com.ifsaid.shark.common.mapper.BaseMapper
  not-empty: false
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.ifsaid.shark.mapper: debug


# JWT 认证配置
jwt:
  tokenHeader: Authorization   #请求头
  secret: w-eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3JlYXRlZCI6MTU0MDYxMzI4N  #加密的字符串
  expiration: 7200000    #毫秒，这里默认2小时
  tokenHead: "Bearer "


info:
  app:
    name: ${spring.application.name}
    description: spring-restful-api
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
